import { makeStyles } from "@material-ui/core";

export const useStyles = makeStyles(({ shadows, palette, breakpoints }) => ({
  modal: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  paper: {
    backgroundColor: "#FFFFFF",
    boxShadow: shadows[5],
    borderRadius: "14px",
    maxWidth: "802px",
    width: "95%",
    padding: "57px 50px 45px 50px",
    outline: "none",
    display: "flex",
    flexDirection: "column",
    gap: "33px",
    maxHeight: window.innerHeight - 50,
    overflow: "auto",
    [breakpoints.down("xs")]: {
      padding: "30px 20px 20px 20px",
    },
  },
  title: { fontWeight: 600, fontSize: "20px", marginBottom: "9px" },
  subHeading: { fontSize: "14px", fontWeight: 400, color: "#171B1E80" },
  subTitle: {
    fontSize: "16px",
    fontWeight: 400,
    color: "#171B1E80",
    marginBottom: "13px",
  },
  iconBtn: {
    cursor: "pointer",
    transition: "0.3s",
    "&:hover": {
      opacity: "0.7",
    },
  },
  titleWrapper: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  ownerName: { fontSize: "14px", fontWeight: 500 },
  ownerWork: { fontSize: "13px", fontWeight: 400, opacity: 0.5 },
  avatarWrapper: {
    height: "64px",
    width: "64px",
    background: "#E6646E36",
    borderRadius: "5px",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
    marginRight: "11px",
  },
  cancelBtn: {
    color: "#171B1E80",
    background: `${palette.all.gray}14`,
    height: "40px",
    width: "99px",
    borderRadius: "8px",
  },
  submitBtn: {
    color: "#FFF",
    background: palette.all.blue,
    height: "40px",
    width: "99px",
    borderRadius: "8px",
  },
  textArea: {
    width: "100%",
    borderRadius: "14px",
    padding: "12px 23px",
    fontSize: "16px",
    border: "1px solid #9C969E80",
    outline: "none",
  },
  formWrapper: {
    display: "flex",
    flexWrap: "wrap",
    gap: "32px",
    "& > div": { width: "calc(50% - 16px)" },
    [breakpoints.down("xs")]: {
      flexDirection: "column",
      "& > div": { width: "100%" },
    },
  },
  dropDown: {
    position: "relative",
    padding: "16px 23px",
    fontSize: "16px",
    fontWeight: 400,
    borderRadius: "12px",
    border: "1px solid #D7D7D7",
    cursor: "pointer",
    height: "60px",
  },
  txtField: {
    height: "60px",
    width: "100%",
    fontSize: "16px",
    fontWeight: 400,
    borderRadius: "12px",
    "& input[type=number]": {
      "-moz-appearance": "textfield",
    },
    "& input[type=number]::-webkit-outer-spin-button": {
      "-webkit-appearance": "none",
      margin: 0,
    },
    "& input[type=number]::-webkit-inner-spin-button": {
      "-webkit-appearance": "none",
      margin: 0,
    },
  },
  arrowIcon: {
    position: "absolute",
    right: "20px",
    top: "0",
    height: "-webkit-fill-available",
    display: "flex",
    alignItems: "center",
  },
}));
